// This file contains the full periodic table data for 118 elements
// Each element: number, symbol, name, group, period, category
export const FULL_ELEMENTS = [
  { number: 1, symbol: 'H', name: 'Hydrogen', group: 1, period: 1, category: 'nonmetal' },
  { number: 2, symbol: 'He', name: 'Helium', group: 18, period: 1, category: 'noble gas' },
  { number: 3, symbol: 'Li', name: 'Lithium', group: 1, period: 2, category: 'alkali metal' },
  { number: 4, symbol: 'Be', name: 'Beryllium', group: 2, period: 2, category: 'alkaline earth metal' },
  { number: 5, symbol: 'B', name: 'Boron', group: 13, period: 2, category: 'metalloid' },
  { number: 6, symbol: 'C', name: 'Carbon', group: 14, period: 2, category: 'nonmetal' },
  { number: 7, symbol: 'N', name: 'Nitrogen', group: 15, period: 2, category: 'nonmetal' },
  { number: 8, symbol: 'O', name: 'Oxygen', group: 16, period: 2, category: 'nonmetal' },
  { number: 9, symbol: 'F', name: 'Fluorine', group: 17, period: 2, category: 'halogen' },
  { number: 10, symbol: 'Ne', name: 'Neon', group: 18, period: 2, category: 'noble gas' },
  { number: 11, symbol: 'Na', name: 'Sodium', group: 1, period: 3, category: 'alkali metal' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', group: 2, period: 3, category: 'alkaline earth metal' },
  { number: 13, symbol: 'Al', name: 'Aluminum', group: 13, period: 3, category: 'post-transition metal' },
  { number: 14, symbol: 'Si', name: 'Silicon', group: 14, period: 3, category: 'metalloid' },
  { number: 15, symbol: 'P', name: 'Phosphorus', group: 15, period: 3, category: 'nonmetal' },
  { number: 16, symbol: 'S', name: 'Sulfur', group: 16, period: 3, category: 'nonmetal' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', group: 17, period: 3, category: 'halogen' },
  { number: 18, symbol: 'Ar', name: 'Argon', group: 18, period: 3, category: 'noble gas' },
  { number: 19, symbol: 'K', name: 'Potassium', group: 1, period: 4, category: 'alkali metal' },
  { number: 20, symbol: 'Ca', name: 'Calcium', group: 2, period: 4, category: 'alkaline earth metal' },
  { number: 21, symbol: 'Sc', name: 'Scandium', group: 3, period: 4, category: 'transition metal' },
  { number: 22, symbol: 'Ti', name: 'Titanium', group: 4, period: 4, category: 'transition metal' },
  { number: 23, symbol: 'V', name: 'Vanadium', group: 5, period: 4, category: 'transition metal' },
  { number: 24, symbol: 'Cr', name: 'Chromium', group: 6, period: 4, category: 'transition metal' },
  { number: 25, symbol: 'Mn', name: 'Manganese', group: 7, period: 4, category: 'transition metal' },
  { number: 26, symbol: 'Fe', name: 'Iron', group: 8, period: 4, category: 'transition metal' },
  { number: 27, symbol: 'Co', name: 'Cobalt', group: 9, period: 4, category: 'transition metal' },
  { number: 28, symbol: 'Ni', name: 'Nickel', group: 10, period: 4, category: 'transition metal' },
  { number: 29, symbol: 'Cu', name: 'Copper', group: 11, period: 4, category: 'transition metal' },
  { number: 30, symbol: 'Zn', name: 'Zinc', group: 12, period: 4, category: 'post-transition metal' },
  { number: 31, symbol: 'Ga', name: 'Gallium', group: 13, period: 4, category: 'post-transition metal' },
  { number: 32, symbol: 'Ge', name: 'Germanium', group: 14, period: 4, category: 'metalloid' },
  { number: 33, symbol: 'As', name: 'Arsenic', group: 15, period: 4, category: 'metalloid' },
  { number: 34, symbol: 'Se', name: 'Selenium', group: 16, period: 4, category: 'nonmetal' },
  { number: 35, symbol: 'Br', name: 'Bromine', group: 17, period: 4, category: 'halogen' },
  { number: 36, symbol: 'Kr', name: 'Krypton', group: 18, period: 4, category: 'noble gas' },
  { number: 37, symbol: 'Rb', name: 'Rubidium', group: 1, period: 5, category: 'alkali metal' },
  { number: 38, symbol: 'Sr', name: 'Strontium', group: 2, period: 5, category: 'alkaline earth metal' },
  { number: 39, symbol: 'Y', name: 'Yttrium', group: 3, period: 5, category: 'transition metal' },
  { number: 40, symbol: 'Zr', name: 'Zirconium', group: 4, period: 5, category: 'transition metal' },
  { number: 41, symbol: 'Nb', name: 'Niobium', group: 5, period: 5, category: 'transition metal' },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', group: 6, period: 5, category: 'transition metal' },
  { number: 43, symbol: 'Tc', name: 'Technetium', group: 7, period: 5, category: 'transition metal' },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', group: 8, period: 5, category: 'transition metal' },
  { number: 45, symbol: 'Rh', name: 'Rhodium', group: 9, period: 5, category: 'transition metal' },
  { number: 46, symbol: 'Pd', name: 'Palladium', group: 10, period: 5, category: 'transition metal' },
  { number: 47, symbol: 'Ag', name: 'Silver', group: 11, period: 5, category: 'transition metal' },
  { number: 48, symbol: 'Cd', name: 'Cadmium', group: 12, period: 5, category: 'post-transition metal' },
  { number: 49, symbol: 'In', name: 'Indium', group: 13, period: 5, category: 'post-transition metal' },
  { number: 50, symbol: 'Sn', name: 'Tin', group: 14, period: 5, category: 'post-transition metal' },
  { number: 51, symbol: 'Sb', name: 'Antimony', group: 15, period: 5, category: 'metalloid' },
  { number: 52, symbol: 'Te', name: 'Tellurium', group: 16, period: 5, category: 'metalloid' },
  { number: 53, symbol: 'I', name: 'Iodine', group: 17, period: 5, category: 'halogen' },
  { number: 54, symbol: 'Xe', name: 'Xenon', group: 18, period: 5, category: 'noble gas' },
  { number: 55, symbol: 'Cs', name: 'Cesium', group: 1, period: 6, category: 'alkali metal' },
  { number: 56, symbol: 'Ba', name: 'Barium', group: 2, period: 6, category: 'alkaline earth metal' },
  { number: 57, symbol: 'La', name: 'Lanthanum', group: 3, period: 6, category: 'lanthanide' },
  { number: 58, symbol: 'Ce', name: 'Cerium', group: 3, period: 6, category: 'lanthanide' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', group: 3, period: 6, category: 'lanthanide' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', group: 3, period: 6, category: 'lanthanide' },
  { number: 61, symbol: 'Pm', name: 'Promethium', group: 3, period: 6, category: 'lanthanide' },
  { number: 62, symbol: 'Sm', name: 'Samarium', group: 3, period: 6, category: 'lanthanide' },
  { number: 63, symbol: 'Eu', name: 'Europium', group: 3, period: 6, category: 'lanthanide' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', group: 3, period: 6, category: 'lanthanide' },
  { number: 65, symbol: 'Tb', name: 'Terbium', group: 3, period: 6, category: 'lanthanide' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', group: 3, period: 6, category: 'lanthanide' },
  { number: 67, symbol: 'Ho', name: 'Holmium', group: 3, period: 6, category: 'lanthanide' },
  { number: 68, symbol: 'Er', name: 'Erbium', group: 3, period: 6, category: 'lanthanide' },
  { number: 69, symbol: 'Tm', name: 'Thulium', group: 3, period: 6, category: 'lanthanide' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', group: 3, period: 6, category: 'lanthanide' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', group: 3, period: 6, category: 'lanthanide' },
  { number: 72, symbol: 'Hf', name: 'Hafnium', group: 4, period: 6, category: 'transition metal' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', group: 5, period: 6, category: 'transition metal' },
  { number: 74, symbol: 'W', name: 'Tungsten', group: 6, period: 6, category: 'transition metal' },
  { number: 75, symbol: 'Re', name: 'Rhenium', group: 7, period: 6, category: 'transition metal' },
  { number: 76, symbol: 'Os', name: 'Osmium', group: 8, period: 6, category: 'transition metal' },
  { number: 77, symbol: 'Ir', name: 'Iridium', group: 9, period: 6, category: 'transition metal' },
  { number: 78, symbol: 'Pt', name: 'Platinum', group: 10, period: 6, category: 'transition metal' },
  { number: 79, symbol: 'Au', name: 'Gold', group: 11, period: 6, category: 'transition metal' },
  { number: 80, symbol: 'Hg', name: 'Mercury', group: 12, period: 6, category: 'post-transition metal' },
  { number: 81, symbol: 'Tl', name: 'Thallium', group: 13, period: 6, category: 'post-transition metal' },
  { number: 82, symbol: 'Pb', name: 'Lead', group: 14, period: 6, category: 'post-transition metal' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', group: 15, period: 6, category: 'post-transition metal' },
  { number: 84, symbol: 'Po', name: 'Polonium', group: 16, period: 6, category: 'post-transition metal' },
  { number: 85, symbol: 'At', name: 'Astatine', group: 17, period: 6, category: 'halogen' },
  { number: 86, symbol: 'Rn', name: 'Radon', group: 18, period: 6, category: 'noble gas' },
  { number: 87, symbol: 'Fr', name: 'Francium', group: 1, period: 7, category: 'alkali metal' },
  { number: 88, symbol: 'Ra', name: 'Radium', group: 2, period: 7, category: 'alkaline earth metal' },
  { number: 89, symbol: 'Ac', name: 'Actinium', group: 3, period: 7, category: 'actinide' },
  { number: 90, symbol: 'Th', name: 'Thorium', group: 3, period: 7, category: 'actinide' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', group: 3, period: 7, category: 'actinide' },
  { number: 92, symbol: 'U', name: 'Uranium', group: 3, period: 7, category: 'actinide' },
  { number: 93, symbol: 'Np', name: 'Neptunium', group: 3, period: 7, category: 'actinide' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', group: 3, period: 7, category: 'actinide' },
  { number: 95, symbol: 'Am', name: 'Americium', group: 3, period: 7, category: 'actinide' },
  { number: 96, symbol: 'Cm', name: 'Curium', group: 3, period: 7, category: 'actinide' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', group: 3, period: 7, category: 'actinide' },
  { number: 98, symbol: 'Cf', name: 'Californium', group: 3, period: 7, category: 'actinide' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', group: 3, period: 7, category: 'actinide' },
  { number: 100, symbol: 'Fm', name: 'Fermium', group: 3, period: 7, category: 'actinide' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', group: 3, period: 7, category: 'actinide' },
  { number: 102, symbol: 'No', name: 'Nobelium', group: 3, period: 7, category: 'actinide' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', group: 3, period: 7, category: 'actinide' },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', group: 4, period: 7, category: 'transition metal' },
  { number: 105, symbol: 'Db', name: 'Dubnium', group: 5, period: 7, category: 'transition metal' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', group: 6, period: 7, category: 'transition metal' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', group: 7, period: 7, category: 'transition metal' },
  { number: 108, symbol: 'Hs', name: 'Hassium', group: 8, period: 7, category: 'transition metal' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', group: 9, period: 7, category: 'unknown' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', group: 10, period: 7, category: 'unknown' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', group: 11, period: 7, category: 'unknown' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', group: 12, period: 7, category: 'post-transition metal' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', group: 13, period: 7, category: 'unknown' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', group: 14, period: 7, category: 'post-transition metal' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', group: 15, period: 7, category: 'unknown' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', group: 16, period: 7, category: 'post-transition metal' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', group: 17, period: 7, category: 'halogen' },
  { number: 118, symbol: 'Og', name: 'Oganesson', group: 18, period: 7, category: 'noble gas' }
];
